version: '3'

services:

  database:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wktest
      MYSQL_DATABASE: wktest
      MYSQL_USER: wktest
      MYSQL_PASSWORD: wktest
      
  backend:
    build:
      context: ./backend
    ports:
      - "8081:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/wktest
      SPRING_DATASOURCE_USERNAME: wktest
      SPRING_DATASOURCE_PASSWORD: wktest

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h database -u root -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: on-failure

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"